---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: CONTENT
- type: directory
  path: content/persons
  label: Persons
  create: documents
  match: "**/*"
  templates:
  - persontemplate
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - test
- type: directory
  path: content/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - template_post
- type: directory
  path: content/services
  label: Services
  create: documents
  match: "**/*"
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
- type: heading
  label: DOCUMENTATION
- type: document
  path: README-CMS.md
  label: Help
  read_only: true
- type: document
  path: changelog.md
  label: Changelog
  read_only: true
upload_dir: uploads
public_path: uploads
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn start
