---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/sundays
  label: sundays
  create: documents
  match: "**/*"
  templates:
  - contentpage
- type: directory
  path: content/resources
  label: resources
  create: documents
  match: "**/*"
  templates:
  - contentpage
- type: directory
  path: content/news
  label: news
  create: documents
  match: "**/*"
  templates:
  - contentpage
- type: directory
  path: content/ministries
  label: ministries
  create: documents
  match: "**/*"
  templates:
  - contentpage
- type: directory
  path: content/getinvolved
  label: getinvolved
  create: documents
  match: "**/*"
  templates:
  - contentpage
- type: directory
  path: content/about
  label: about
  create: documents
  match: "**/*"
  templates:
  - contentpage
  - contentpage
upload_dir: https://stbarnabas-stl.s3.us-east-2.amazonaws.com
public_path: https://stbarnabas-stl.s3.us-east-2.amazonaws.com
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
